project/src/cart/api/urls.py
from django.urls import path, reverse
from . import views

app_name = "cart_api"

urlpatterns = [
    path(
        '',
        views.CartListCreateAPIView.as_view(),
        name='cart_list_create_api'
    ),
    path(
        '<uuid:cart_id>/',
        views.CartItemCreateAPIView.as_view(),
        name='cart_item_create_api'
    ),
    path(
        '<uuid:cart_id>/menu/<int:menu_id>/',
        views.CartItemUpdateAPIView.as_view(),
        name='cart_item_update_delete_api'
    ),
    path(
        '<uuid:cart_id>/delete/',
        views.CartDeleteAPIView.as_view(),
        name='cart_delete_api'
    ),

    path(
        '<uuid:cart_id>/menu/<int:menu_id>/delete/',
        views.CartItemDeleteAPIView.as_view(),
        name='cart_item_delete_api'
    ),
    path(
        '<uuid:cart_id>/update/',
        views.CartItemUpdateAPIView.as_view(),
        name='cart_item_update_api'
    ),
    path(
        'quantity/',
        views.CartItemQuantityAPIView.as_view(),
        name='cart_item_quantity_api'
    ),

]

project/src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [

    path(
        '',
        views.CartView.as_view(),
        name='cart_menu_list'
    )

]

project/src/cart/models.py
import uuid

from django.conf import settings
from django.db import models
from django.db.models import F, IntegerField, Sum
from django.utils.functional import cached_property

from config.common_models import TimeStampedModel
from menu.models import Menu

User = settings.AUTH_USER_MODEL


class Cart(TimeStampedModel):
    id = models.UUIDField(
        verbose_name="Cart 식별번호",
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    user = models.ForeignKey(
        User,
        verbose_name='주문자',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return str(self.user.username) + " - " + str(self.id)

    @cached_property
    def total_price(self):
        '''
        주문함에 담긴 메뉴들의 총 가격을 리턴
        '''
        total = 0
        cart_items = CartItem.objects.select_related('menu').filter(cart=self)

        for cart_item in cart_items:
            total += (cart_item.menu.price * cart_item.quantity)
        return total

    @cached_property
    def total_quantity(self):
        '''
        주문함에 담긴 메뉴들의 총 메뉴 개수를 리턴
        '''
        return sum(list(self.cartitem_set.all().values_list(
            'quantity',
            flat=True
        )))


class CartItemQuerySet(models.QuerySet):
    def filtering_user(self, logged_in_user):
        return (self.select_related(
            'menu',
            'cart'
        ).annotate(
            user=F('cart__user'),
            subtotal_price=Sum(
                F('menu__price') * F('quantity'),
                output_field=IntegerField()
            )
        ).filter(
            user=logged_in_user.id
        ).values(
            'cart_id',
            'menu__id',
            'menu__name',
            'menu__detail',
            'menu__img',
            'quantity',
            'menu__price',
            'subtotal_price'
        )
        )


class CartItemManager(models.Manager):
    def get_queryset(self):
        return CartItemQuerySet(
            self.model,
            using=self._db
        )

    def filtering_user(self, logged_in_user):
        return self.get_queryset().filtering_user(logged_in_user)


class CartItem(models.Model):
    menu = models.ForeignKey(
        Menu,
        verbose_name="Cart에 담긴 메뉴",
        on_delete=models.CASCADE
    )
    cart = models.ForeignKey(
        Cart,
        verbose_name="Cart Item 들을 담는 카트",
        on_delete=models.CASCADE
    )
    quantity = models.PositiveSmallIntegerField(
        "특정 Menu의 개수",
        default=1
    )
    objects = CartItemManager()

    def __str__(self):
        return self.menu.name + ' - ' + str(self.quantity)

    @cached_property
    def subtotal_price(self):
        '''
        주문함에 담긴 특정 메뉴들 가격을 리턴
        '''
        return self.menu.price * self.quantity

project/src/cart/forms.py
from django import forms

from cart.models import Cart, CartItem


class CartModelForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ('user',)


class CartItemModelForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ('cart', 'menu')


class CartItemUpdateModelForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ('quantity', 'menu')

    def clean_quantity(self):
        quantity = self.cleaned_data.get('quantity')
        if quantity > 100 or quantity < 1:
            raise forms.ValidationError('quantity의 개수가 올바르지 않습니다.')
        return quantity

project/src/cart/api/views.py
import json
from http import HTTPStatus

from django.http import JsonResponse
from django.urls import reverse
from django.views.generic import View
from django_bulk_update.helper import bulk_update

from accounts.mixins import LoginRequiredMixin
from cart.forms import (
    CartModelForm,
    CartItemModelForm,
    CartItemUpdateModelForm
)
from cart.models import Cart, CartItem
from menu.models import Menu


class CartItemQuantityAPIView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            cart_obj = self.request.user.cart_set.order_by('-created_time')[0]
        except IndexError:
            return JsonResponse(
                status=HTTPStatus.OK,
                data={
                    "total_quantity": 0
                }
            )

        return JsonResponse(
            status=HTTPStatus.OK,
            data={
                "cart_id": cart_obj.id,
                "total_quantity": cart_obj.total_quantity
            }
        )


class CartListCreateAPIView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        '''
        주문표 내 메뉴의 리스트를 보여준다.
        '''
        cart_obj = self.request.user.cart_set.order_by('-created_time')[0]
        cart_items = (
            CartItem.objects.select_related(
                'menu',
                'menu__restaurant'
            ).prefetch_related('menu__tastes')
                .filter(cart__id=cart_obj.id)
        )

        if not cart_items.exists():
            return JsonResponse(
                data={
                    'message': '주문표는 현재 비어있습니다.'
                }
            )

        first_menu = cart_items.first()

        cart_info = {
            'cart_id': first_menu.cart.id,
            'order_start_url': '',
            'home_url': reverse('home'),
            'total_price': first_menu.cart.total_price,
            'total_quantity': first_menu.cart.total_quantity,
            'delete_url': reverse('cart_api:cart_delete_api',
                                  kwargs={'cart_id': first_menu.cart.id}
                                  )
        }

        menus_in_cart = [
            {
                'id': cart_item.menu.id,
                'img': cart_item.menu.img.url,
                'name': cart_item.menu.name,
                'description': cart_item.menu.detail,
                'price': cart_item.menu.price,
                'quantity': cart_item.quantity,
                'subtotal': cart_item.subtotal_price,
                'taste': ''
            }
            for cart_item in cart_items
        ]

        for index, cart_item in enumerate(cart_items):
            temp_taste_list = []
            for taste in cart_item.menu.tastes.all():
                temp_taste_list.append(taste.name)
            menus_in_cart[index]['taste'] = temp_taste_list

        restaurant = first_menu.menu.restaurant
        restaurant_info = {
            'id': restaurant.id,
            'name': restaurant.name,
            'min_order_price': restaurant.min_order_price,
            'menu': menus_in_cart
        }
        json_data = {
            'cart': cart_info,
            'restaurant': restaurant_info
        }

        return JsonResponse(
            status=HTTPStatus.OK,
            data=json_data,
        )

    def post(self, request, *args, **kwargs):
        '''
        주문표을 생성한다.
        '''
        try:
            cart_data = json.loads(request.body)
        except ValueError:
            return JsonResponse(
                status=HTTPStatus.BAD_REQUEST,
                data={
                    'message': '잘못된 요청 입니다.'
                }
            )
        form = CartModelForm(cart_data)

        if form.is_valid():
            cart_obj = form.save(commit=True)
            json_data = {
                'cart_id': cart_obj.id,
                'user': cart_obj.user.username
            }
            return JsonResponse(
                status=HTTPStatus.CREATED,
                data=json_data,
            )

        return JsonResponse(
            status=HTTPStatus.BAD_REQUEST,
            data={
                'message': '유효 하지 않은 폼 형식 혹은 해당 유저는 이미 생성된 Cart가 있습니다.'
            }
        )


class CartItemCreateAPIView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        '''
        주문표에 메뉴를 추가한다.
        '''
        try:
            cart_data = json.loads(request.body)
        except ValueError:
            return JsonResponse(
                status=HTTPStatus.BAD_REQUEST,
                data={
                    'message': '잘못된 요청 입니다.'
                }
            )
        form = CartItemModelForm(cart_data)

        if not form.is_valid():
            return JsonResponse(
                status=HTTPStatus.BAD_REQUEST,
                data={
                    'message': '유효하지않은 폼 형식 입니다.'
                }
            )

        cart_item_list = list(
            CartItem.objects.select_related(
                'menu__restaurant',
                'cart'
            ).filter(
                cart__id=cart_data['cart'],
            ).values('menu', 'menu__restaurant')
        )

        if cart_item_list:
            new_cart_item_restaurant_id = Menu.objects.filter(id=cart_data['menu']).first().restaurant_id

            if new_cart_item_restaurant_id is not cart_item_list[0]['menu__restaurant']:
                return JsonResponse(
                    status=HTTPStatus.BAD_REQUEST,
                    data={
                        'message': '다른 레스토랑의 메뉴는 주문함에 담을 수 없습니다.'
                    }
                )

            if cart_data['menu'] in [(lambda element: element['menu'])(cart_item) for cart_item in cart_item_list]:
                return JsonResponse(
                    status=HTTPStatus.BAD_REQUEST,
                    data={
                        'message': '중복된 메뉴 입니다.'
                    }
                )

        cart_item = form.save(commit=True)
        json_data = {
            'menu_id': cart_item.menu.id,
            'cart_id': cart_item.cart.id,
            'menu_name': cart_item.menu.name,
            'total_quantity': cart_item.cart.total_quantity
        }
        return JsonResponse(
            status=HTTPStatus.CREATED,
            data=json_data,
        )


class CartItemDeleteAPIView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        '''
        주문표의 특정 메뉴를 삭제한다.
        '''
        try:
            cart_item_obj = CartItem.objects.get(
                cart__id=self.kwargs['cart_id'],
                menu__id=self.kwargs['menu_id']
            )
        except CartItem.DoesNotExist:
            return JsonResponse(
                status=HTTPStatus.NOT_FOUND,
                data={
                    'message': '주문표에 해당하는 메뉴가 없습니다.'
                }
            )
        else:
            cart_item_obj.delete()

        return JsonResponse(
            status=HTTPStatus.OK,
            data={
                'message': '성공적으로 삭제하였습니다.',
                'subtotal': cart_item_obj.subtotal_price,
                'total_price': cart_item_obj.cart.total_price,
                'total_quantity': cart_item_obj.cart.total_quantity
            }
        )


class CartDeleteAPIView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        '''
        주문표를 삭제한다.
        '''
        try:
            cart_obj = Cart.objects.get(
                id=self.kwargs['cart_id']
            )
        except Cart.DoesNotExist:
            return JsonResponse(
                status=HTTPStatus.NOT_FOUND,
                data={
                    'message': '해당하는 주문표가 존재하지 않습니다.',
                }
            )
        else:
            cart_obj.delete()
            new_cart = Cart.objects.create(user=self.request.user)

        return JsonResponse(
            status=HTTPStatus.OK,
            data={
                'message': '주문표는 현재 비어있습니다.',
                'total_quantity': cart_obj.total_quantity,
                'cart_id': new_cart.id
            }
        )


class CartItemUpdateAPIView(LoginRequiredMixin, View):
    def put(self, request, *args, **kwargs):
        '''
        Cart 내 메뉴 개수를 조정한다.
        '''
        try:
            json_datas = json.loads(request.body)
        except ValueError:
            return JsonResponse(
                status=HTTPStatus.BAD_REQUEST,
                data={
                    'message': '잘못된 요청 입니다.'
                }
            )

        cart_items = CartItem.objects.select_related('menu', 'cart').filter(
            cart__id=self.kwargs['cart_id'],
        )

        for json_data in json_datas:
            form = CartItemUpdateModelForm(
                json_data,
            )
            if form.is_valid():
                for cart_item in cart_items:
                    if cart_item.menu.id == json_data['menu']:
                        cart_item.quantity = json_data['quantity']
            else:
                return JsonResponse(
                    status=HTTPStatus.BAD_REQUEST,
                    data={
                        'message': '폼이 유효하지 않습니다.',
                        'error': form.errors
                    }
                )

        bulk_update(cart_items, update_fields=['quantity'])

        return JsonResponse(
            status=HTTPStatus.OK,
            data={
                'message': '메뉴가 성공적으로 추가되었습니다.',
                'subtotal': cart_items[0].subtotal_price,
                'total_price': cart_items[0].cart.total_price,
                'total_quantity': cart_items[0].cart.total_quantity
            },
        )

project/src/cart/views.py
from django.views.generic import TemplateView


class CartView(TemplateView):
    template_name = 'cart/cart_list.html'

project/src/templates/cart/cart_list.html
{% extends 'common/base.html' %}

{% load static %}

{% block base_head %}

{% endblock %}

{% block content %}
    <div id="main">
        <h1><i class="fas fa-shopping-cart"></i> {{ request.user }} 님의 주문표 </h1>
        <hr>
        <br>
        <div id=restaurant-info>

        </div>
        <table id="cart" class="table table-hover table-condensed">
            <thead>
            <tr>
                <th class="text-space">&nbsp;&nbsp;메뉴</th>
                <th style="width:10%" class="text-space">&nbsp;&nbsp;가격</t>
                <th style="width:13%" class="text-center">수량</th>
                <th style="width:15%" class="text-center">
                    가격 x 수량
                </th>
                <th style="width:13%" class="text-center">삭제</th>
            </tr>
            </thead>


            <tbody id="menu-table"></tbody>

            <tfoot id="cart-info">

            </tfoot>
        </table>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $.ajax({
                url: '{% url "cart_api:cart_list_create_api" %}',
                method: "GET",
                success: function (data) {
                    if (data.message) {
                        $("#main").append(
                            `<div style="text-align:center;">
                                <h3>` + data.message + `</h3>
                            </div>`
                        )
                    } else {
                        var cart_id = data.cart.cart_id

                        //레스토랑 정보
                        var restaurant_name = data.restaurant.name
                        var min_order_price = data.restaurant.min_order_price
                        $('#restaurant-info').append(
                            `<h3>` + restaurant_name + "   " + `<button onclick="deleteCart(` + "'" + data.cart.delete_url + "'" + `)" class="badge badge-primary"> <i class="fas fa-trash-alt"></i> </a></h3>
                        <span class="badge badge-primary">최소 주문 금액 : ` + min_order_price + `</span>
                        <input type="hidden" id="menu-count" value=` + data.restaurant.menu.length + `>
                        <br>
                        <br>`
                        )
                        //메뉴 정보
                        $.each(data.restaurant.menu, function (key, value) {
                            var menu_id = value.id
                            var menu_name = value.name;
                            var menu_description = value.description;
                            var menu_price = value.price;
                            var menu_quantity = value.quantity;
                            var menu_subtotal = value.subtotal;
                            var menu_img = value.img;
                            $("#menu-table").append(
                                `<tr id="menu-row-` + menu_id + `">
                                    <td data-th="메뉴">
                                        <div class="row">
                                            <div class="col-sm-3 hidden-xs">
                                                
                                                <img src=` + menu_img + ` alt="..." width=100 height=100
                                                    class="img-responsive" />
                                                
                                            </div>
                                            <div class="col-sm-7">
                                                <input type="hidden" id="menu-` + menu_id + `" value=` + menu_id + `>
                                                <h4 class="nomargin">` + menu_name + `</h4>
                                                <p>` + menu_description + `</p>
                                                <div>
                                                    <div id="tastes-` + menu_id + `" class="row">
                                                        
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td id="menu-price-` + menu_id + `" data-th="Price" withd="10%">￦ ` + menu_price + `</td>
                                        <td id="menu-quantity-` + menu_id + `" data-th="Quantity" class="text-center">` + menu_quantity + `
                                            <div>
                                                <div class="row center">
                                                    <button onclick="upQuantity(` + menu_id + `)" id="quantity-plus-button" class="badge badge-success"> 
                                                        <i class="fas fa-plus"></i>
                                                    </button>
                                                        &nbsp;&nbsp;
                                                    <button onclick="downQuantity(` + menu_id + `)" id="quantity-minus-button" class="badge badge-success"> 
                                                        <i class="fas fa-minus"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </td>
                                    
                                        
                                    <td id="menu-subtotal-` + menu_id + `" data-th="Subtotal" class="text-center">
                                        ￦ ` + menu_subtotal + `
                                    </td>
                                    <td id="menu-delete-` + menu_id + `" class="text-center" class="actions" data-th="">
                                        <button onclick="deleteCartItem(` + "'" + cart_id + "'" + `,` + menu_id + ',' + menu_id + `)" class="btn btn-danger btn-sm">
                                            <i class="fas fa-times"></i>
                                        </button>
                                    </td>
                                </tr>`
                            )

                            $.each(value.taste, function (key, value) {
                                var taste = value
                                $("#tastes-" + menu_id).append(
                                    `<span class="badge badge-pill badge-dark">` + taste + `</span>&nbsp;`
                                )
                            })

                        })
                    }
                    // 주문표 관련 정보
                    var home_url = data.cart.home_url;
                    var total_price = data.cart.total_price;
                    var total_quantity = data.cart.total_quantity;
                    var menus = data.restaurant.menu


                    menu_list = []
                    data.restaurant.menu.map((data) => {
                        menu_list.push(data.id)
                    })

                    $("#cart-info").append(
                        `<tr>
                        <td>
                            <a href=` + home_url + ` class="btn btn-warning"><i class="fa fa-angle-left"></i> 홈으로 이동</a>
                        </td>
                        <td colspan="1" class="hidden-xs"></td>
                        <td class="hidden-xs text-center">
                            <p id="total-quantity" class="total">총 메뉴 수: ` + total_quantity + `</p>
                        </td>
                        <td class="hidden-xs text-center">
                            <p id="total-price" class="total">총 가격: ￦ ` + total_price + `</p>
                        </td>
                        <td>
                            <button onclick= "updateQuantity(` + "'" + encodeURIComponent(menu_list) + "'" + "," + "'" + cart_id + "'" + `,` + "1" + `)" class="btn btn-success btn-block">저장 하기 <i class="fa fa-angle-right"></i></a>
                            <button onclick= "updateQuantity(` + "'" + encodeURIComponent(menu_list) + "'" + "," + "'" + cart_id + "'" + `,` + "2" + `)" class="btn btn-warning btn-block">주문 하기 <i class="fa fa-angle-right"></i></a>
                        </td>
                        
                    </tr>`
                    )
                },
                error: function (data) {
                    $("#main").empty()
                    $("#main").append(
                        `<h1>잘못된 접근 입니다.</h1>`
                    )
                }
            })
        });
    </script>
{% endblock %}